{{ if and .Values.wso2.deployment.persistence.solrIndexing.enabled .Values.aws.enabled }}
# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-local-carbon-database-1
  labels:
    purpose: cp-carbondb-1
spec:
  capacity:
    storage: {{ .Values.aws.efs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-cp.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.aws.efs.fileSystemId }}::{{ .Values.aws.efs.accessPoints.carbonDb1 }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-solr-indexed-data-1
  labels:
    purpose: cp-solr-1
spec:
  capacity:
    storage: {{ .Values.aws.efs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-cp.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.aws.efs.fileSystemId }}::{{ .Values.aws.efs.accessPoints.solr1 }}

---
{{ if .Values.wso2.deployment.highAvailability }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-local-carbon-database-2
  labels:
    purpose: cp-carbondb-2
spec:
  capacity:
    storage: {{ .Values.aws.efs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-cp.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.aws.efs.fileSystemId }}::{{ .Values.aws.efs.accessPoints.carbonDb2 }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-solr-indexed-data-2
  labels:
    purpose: cp-solr-2
spec:
  capacity:
    storage: {{ .Values.aws.efs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-cp.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.aws.efs.fileSystemId }}::{{ .Values.aws.efs.accessPoints.solr2 }}
{{- end }}
{{- end }}
