# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{ if and .Values.wso2.deployment.persistence.solrIndexing.enabled .Values.gcp.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-local-carbon-database-1
  labels:
    purpose: am-carbondb-1
spec:
  capacity:
    storage: {{ .Values.gcp.fs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-cp.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/{{ .Values.gcp.fs.location }}/{{ .Values.gcp.fs.fileshares.carbonDB1.fileStoreName }}/{{ .Values.gcp.fs.fileshares.carbonDB1.fileShareName }}"
    volumeAttributes:
      ip: {{ .Values.gcp.fs.fileshares.carbonDB1.ip }}
      volume: {{ .Values.gcp.fs.fileshares.carbonDB1.fileShareName }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-solr-indexed-data-1
  labels:
    purpose: am-solr-1
spec:
  capacity:
    storage: {{ .Values.gcp.fs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-cp.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/{{ .Values.gcp.fs.location }}/{{ .Values.gcp.fs.fileshares.solr1.fileStoreName }}/{{ .Values.gcp.fs.fileshares.solr1.fileShareName }}"
    volumeAttributes:
      ip: {{ .Values.gcp.fs.fileshares.solr1.ip }}
      volume: {{ .Values.gcp.fs.fileshares.solr1.fileShareName }}

---
{{ if .Values.wso2.deployment.highAvailability }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-local-carbon-database-2
  labels:
    purpose: am-carbondb-2
spec:
  capacity:
    storage: {{ .Values.gcp.fs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-cp.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/{{ .Values.gcp.fs.location }}/{{ .Values.gcp.fs.fileshares.carbonDB2.fileStoreName }}/{{ .Values.gcp.fs.fileshares.carbonDB2.fileShareName }}"
    volumeAttributes:
      ip: {{ .Values.gcp.fs.fileshares.carbonDB2.ip }}
      volume: {{ .Values.gcp.fs.fileshares.carbonDB2.fileShareName }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-helm-cp.fullname" . }}-solr-indexed-data-2
  labels:
    purpose: am-solr-2
spec:
  capacity:
    storage: {{ .Values.gcp.fs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "apim-helm-cp.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/{{ .Values.gcp.fs.location }}/{{ .Values.gcp.fs.fileshares.solr2.fileStoreName }}/{{ .Values.gcp.fs.fileshares.solr2.fileShareName }}"
    volumeAttributes:
      ip: {{ .Values.gcp.fs.fileshares.solr2.ip }}
      volume: {{ .Values.gcp.fs.fileshares.solr2.fileShareName }}

{{- end }}
{{- end }}
